version: '2'
services:
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:9.4"
    environment:
     POSTGRES_PASSWORD: 123456
     POSTGRES_USER: postgres
  web:
    image: "nodejs:9.4"
    ports:
     - "80:7777"
    volumes:
     - .:/var/www/node
    depends_on:
      - postgres
      - redis
    command: ["postgres:5432", "--", "npm", "start"]