version: '3.1'

services:
  term:
    image: glud/wetty
    environment:
      WETTY_USER: term
      WETTY_PASSWORD: term
      WETTY_USERS_FILE: /run/secrets/users
    secrets:
      - users

secrets:
  users:
    file: ./users.priv #user:password
